_target_: robots_realtime.envs.launch.LaunchConfig

robots:
  left: ["robot_configs/yam/left.yaml"]
  right: ["robot_configs/yam/left.yaml", "robot_configs/yam/right.yaml"]

agent:
  _target_: robots_realtime.agents.replay_agent.ReplayAgent
  episode_dir: "../xdof_epi/episode_0" # REPLACE THIS with your actual episode path
  loop: false

station_metadata:
  world_frame: "left_arm" # front x, left y, up z
  extrinsics:
    right_arm_extrinsic:
      position: [0.0, -0.61, 0.0]
      rotation: [1.0, 0.0, 0.0, 0.0]

