_target_: robots_realtime.envs.launch.LaunchConfig

sensors:
  cameras:
    top_camera:
      _target_: robots_realtime.sensors.cameras.camera.CameraNode
      camera:
        _target_: robots_realtime.sensors.cameras.realsense_camera.RealSenseCamera
        serial_number: "230322274714"
        name: "top_camera"
    right_camera:
      _target_: robots_realtime.sensors.cameras.camera.CameraNode
      camera:
        _target_: robots_realtime.sensors.cameras.realsense_camera.RealSenseCamera
        serial_number: "230322277156"
        name: "right_camera"
    left_camera:
      _target_: robots_realtime.sensors.cameras.camera.CameraNode
      camera:
        _target_: robots_realtime.sensors.cameras.realsense_camera.RealSenseCamera
        serial_number: "230322271210"
        name: "left_camera"

robots:
  left: ["robot_configs/yam/left.yaml"]
  right: ["robot_configs/yam/left.yaml", "robot_configs/yam/right.yaml"]

agent:
  _target_: robots_realtime.agents.policy_learning.molmoact_agent.MolmoActAgent
  checkpoint: "checkpoints/1228_xdof_bottle_old_pt160k_aug_step76000-hf-16"
  # checkpoint: "checkpoints/1224_throw_bottle_60000/"
  task_description: "throw plastic bottles in bin"
  action_chunk: 16
  debug: false
  motion_tokenizer_checkpoint: checkpoints/xdof_all_cs30_tokenizer/latest.pt
  resize_to_train_shape: true
  train_shape: [224, 168]
  unnorm_key: "flow_tokenized"
  # unnorm_key: "rel_16"
  center_crop_scale: 0.95
  crop_top_only: false

# dataset_observation_dir: "../xdof_epi/throw_bottle_1/" # REPLACE THIS with your actual dataset directory
action_threshold: 1 # Threshold for action comparison (not used with ReplayAgent, but required)
hz: 20
station_metadata:
  world_frame: "left_arm" # front x, left y, up z
  extrinsics:
    right_arm_extrinsic:
      position: [0.0, -0.61, 0.0]
      rotation: [1.0, 0.0, 0.0, 0.0]

reset_pos:
  - 0
  - 0.3973
  - 0.5384
  - -0.1410
  - 0
  - 0
home_pos:
  - 0
  - -0.004
  - 0.1593
  - -0.7712
  - 0.0158
  - -0.0120

max_steps: 5000

