_target_: robots_realtime.envs.launch.LaunchConfig

# sensors:
#   cameras:
#     top_camera:
#         _target_: robots_realtime.sensors.cameras.camera.CameraNode
#         camera:
#             _target_: robots_realtime.sensors.cameras.opencv_camera.OpencvCamera
#             device_path: "/dev/video4"
#             camera_type: "realsense_camera"

robots:
  left: ["robot_configs/yam/left.yaml"]
  # right: ["robot_configs/yam/left.yaml", "robot_configs/yam/right.yaml"]

agent:
  _target_: robots_realtime.agents.teleoperation.yam_pyroki_viser_agent.YamPyrokiViserAgent
  bimanual: false

station_metadata:
  world_frame: "left_arm" # front x, left y, up z

reset_pos:
  - 0
  - 0.3973
  - 0.5384
  - -0.1410
  - 0
  - 0
home_pos:
  - 0
  - -0.004
  - 0.1593
  - -0.7712
  - 0.0158
  - -0.0120